"""Add tables

Revision ID: e29a1062d4a6
Revises: fefd231f4d72
Create Date: 2026-03-10 17:39:00.999057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29a1062d4a6'
down_revision: Union[str, Sequence[str], None] = 'fefd231f4d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('bot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bot_id'),
    sa.UniqueConstraint('bot_token')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.CheckConstraint('length(user_name) >= 4', name='min_user_name_length'),
    sa.CheckConstraint('length(user_password) >= 8', name='min_user_passwrod_length'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('users_bots',
    sa.Column('us_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['b_id'], ['bots.bot_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('us_id'),
    sa.UniqueConstraint('u_id', 'b_id', name='unique_u_id_and_b_id'),
    sa.UniqueConstraint('u_id', 'title', name='unique_u_id_and_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_bots')
    op.drop_table('users')
    op.drop_table('bots')
    # ### end Alembic commands ###
